name: prestige_app
description: Application de gestion Prestige.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Versions Mises à Jour ---
  http: ^1.2.1
  intl: ^0.20.2 # CORRECTION: Version compatible avec le SDK Flutter
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  printing: ^5.14.2
  pdf: ^3.11.0
  fluttertoast: ^8.2.6
  shimmer: ^3.0.0

  # --- Dépendances pour l'export ---
  csv: ^6.0.0
  path_provider: ^2.1.3
  share_plus: ^10.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21